# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-08-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailqueue', '0005_auto_20210606_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedmail',
            name='sender',
            field=models.EmailField(default='Equipe Bike Anjo<noreply@bikeanjo.org>', max_length=254, verbose_name='From'),
        ),
    ]
