# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-08-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0045_auto_20210606_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='Contato', max_length=128, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='closed_by',
            field=models.CharField(blank=True, choices=[('bikeanjo', 'Bike Anjo'), ('requester', 'New cyclist')], max_length=12, verbose_name='Closed by'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('attended', 'Attended'), ('finalized', 'Finished'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('eba', 'Closed by EBA')], default='new', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='target_roles',
            field=models.CharField(choices=[('all', 'All'), ('bikeanjo', 'Bike Anjo'), ('requester', 'New cyclist')], default='all', max_length=16, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='tipforcycling',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tips', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tipforcycling',
            name='target',
            field=models.CharField(choices=[('all', 'All'), ('bikeanjo', 'Bike Anjo'), ('requester', 'New cyclist')], default='all', max_length=16, verbose_name='Target'),
        ),
    ]
