# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-08-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20170809_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideitem',
            name='image',
            field=models.ImageField(upload_to='slides', verbose_name='Image'),
        ),
    ]
